GET http://localhost:4000/api/v1/

###

GET http://localhost:4000/api/v1/company/auth/authUri/5f3ad92fcc9b5ab85785864d
###

POST http://localhost:4000/api/v1/user/signup
content-type: application/json

{
    "username": "wesleylhandy@gmail.com",
    "password": "s0m3un!quePW",
    "confirmPassword": "s0m3un!quePW"
}

###

POST http://localhost:4000/api/v1/user/login
content-type: application/json

{
    "username": "wesleylhandy@gmail.com",
    "password": "s0m3un!quePW"
}

###

POST http://localhost:4000/api/v1/user/login
content-type: application/json

{
    "username": "wesley@wearecreativ.media",
    "password": "s0m3un!quePW"
}

###

GET http://localhost:4000/api/v1/company/db/5f3ad92fcc9b5ab85785864d

###

POST http://localhost:4000/api/v1/company/create
content-type: application/json

{
    "identifier": "Creativ",
    "username": "wesley@wearecreativ.media",
    "password": "s0m3un!quePW",
    "confirmPassword": "s0m3un!quePW"
}

###

GET http://localhost:4000/api/v1/company/db/5f3ad92fcc9b5ab85785864d

###

GET http://localhost:4000/api/v1/company/qb/5f3ad92fcc9b5ab85785864d

###
POST http://localhost:4000/api/v1/company/upload/5f3ad92fcc9b5ab85785864d
content-type: multipart/form-data; boundary=------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; fieldname="image"; filename="handy_profile_colorful.jpg"
Content-Type: image/jpg

< ./handy_profile_colorful.jpg
------WebKitFormBoundary7MA4YWxkTrZu0gW--

###

POST http://localhost:4000/api/v1/customer/transaction/5f3ad09c152b98b3b9908479/5f3ad92fcc9b5ab85785864d
content-type: application/json

{
    "cart": {
        "productName": "Single Ticket",
        "productId": "5f3ad09c152b98b3b9908479",
        "quantity": "1"
    },
    "total": "8.50"
}

###

GET http://localhost:4000/api/v1/company/transactions/5f3ad92fcc9b5ab85785864d