const { connectToDatabase, connection } = require(`./connection`)
const {
  getUserById,
  getUserByUsername,
  getRolesUserById,
  createUser,
  createUserWithRole,
  addCompanyUserRole,
  removeCompanyUserRole,
} = require(`./User`)
const {
  createCompany,
  createCompanyFromRealmId,
  createTemporaryCompany,
  getCompanyByQBORealmId,
  getCompanyByCompanyIdentifier,
  getCompanyByEmail,
  getCompanyById,
  getProductsByRealmId,
  getUsersByRealmId,
  updateTokens,
  updateTokensByRealmId,
  addCompanyInfoFromQBO,
  addCompanyUser,
  removeCompanyUser,
  updateLogo,
  addOrUpdateProduct,
  importProducts,
  removeProduct,
  updateGrabatixIdentifier,
  completeRegistration,
} = require(`./Company`)
const {
  getAllInvitations,
  getInvitationByCode,
  createInvitation,
  inviteInvitation,
  redeemInvitation,
  releaseInvitationByCode,
  releaseInvitationById,
} = require(`./Invitation`)
const { paymentSchema } = require(`./schema/PaymentSchema`)
module.exports = {
  connectToDatabase,
  connection,
  getUserById,
  getUserByUsername,
  getRolesUserById,
  createUser,
  createUserWithRole,
  addCompanyUserRole,
  removeCompanyUserRole,
  createCompany,
  createCompanyFromRealmId,
  createTemporaryCompany,
  getCompanyByQBORealmId,
  getCompanyByCompanyIdentifier,
  getCompanyByEmail,
  getCompanyById,
  getProductsByRealmId,
  getUsersByRealmId,
  updateTokens,
  updateTokensByRealmId,
  addCompanyInfoFromQBO,
  addCompanyUser,
  removeCompanyUser,
  updateLogo,
  addOrUpdateProduct,
  importProducts,
  removeProduct,
  paymentSchema,
  updateGrabatixIdentifier,
  completeRegistration,
  getAllInvitations,
  getInvitationByCode,
  createInvitation,
  inviteInvitation,
  redeemInvitation,
  releaseInvitationByCode,
  releaseInvitationById,
}
